# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='matched_wine',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
