# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20160411_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_picture',
        ),
    ]
