# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_matched_wine'),
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='matched_wine',
            field=models.OneToOneField(blank=True, max_length=500, on_delete=django.db.models.deletion.CASCADE, to='wines.WineNote'),
        ),
    ]
