# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160426_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='matched_wine',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wines.WineNote'),
        ),
    ]
