# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 17:59
from __future__ import unicode_literals

from django.db import migrations
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20160507_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default=b'', editable=False, null=True, serialize=False),
        ),
    ]
