# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_search_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_class', models.CharField(blank=True, max_length=200)),
                ('chef_class', models.CharField(blank=True, max_length=200)),
                ('description_class', models.CharField(blank=True, max_length=200)),
                ('ingredients_class', models.CharField(blank=True, max_length=200)),
                ('method_class', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
