# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_externalrecipe_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_picture_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_picture',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_thumbnail',
            field=models.ImageField(blank=True, upload_to=b'thumbnails'),
        ),
    ]
